### ISSUE TITLE
Network unavailable After connect successfully 

### ISSUE THREAD

**Issue by dannyZhou** [x-falcon/Virtual-Hosts#14]
1. create empty file 
2. select this file 
3. open vpn 
4. open mobile browser
5. open www.baidu.com
6. refresh page.

Network unavailable 

```
01-02 11:20:54.497 2940-3666/com.android.browser W/System.err: java.net.SocketTimeoutException: connect timed out
01-02 11:20:54.499 2940-3666/com.android.browser W/System.err:     at java.net.PlainSocketImpl.socketConnect(Native Method)
01-02 11:20:54.499 2940-3666/com.android.browser W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
01-02 11:20:54.499 2940-3666/com.android.browser W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
01-02 11:20:54.501 2940-3666/com.android.browser W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
01-02 11:20:54.501 2940-3666/com.android.browser W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
01-02 11:20:54.501 2940-3666/com.android.browser W/System.err:     at java.net.Socket.connect(Socket.java:586)
01-02 11:20:54.501 2940-3666/com.android.browser W/System.err:     at okhttp3.internal.AndroidPlatform.connectSocket(SourceFile:55)
01-02 11:20:54.501 2940-3666/com.android.browser W/System.err:     at okhttp3.internal.io.RealConnection.connectSocket(SourceFile:185)
01-02 11:20:54.502 2940-3666/com.android.browser W/System.err:     at okhttp3.internal.io.RealConnection.buildConnection(SourceFile:170)
01-02 11:20:54.502 2940-3666/com.android.browser W/System.err:     at okhttp3.internal.io.RealConnection.connect(SourceFile:111)
01-02 11:20:54.502 2940-3666/com.android.browser W/System.err:     at okhttp3.internal.http.StreamAllocation.findConnection(SourceFile:187)
01-02 11:20:54.502 2940-3666/com.android.browser W/System.err:     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(SourceFile:123)
01-02 11:20:54.502 2940-3666/com.android.browser W/System.err:     at okhttp3.internal.http.StreamAllocation.newStream(SourceFile:93)
01-02 11:20:54.503 2940-3666/com.android.browser W/System.err:     at okhttp3.internal.http.HttpEngine.connect(SourceFile:296)
01-02 11:20:54.503 2940-3666/com.android.browser W/System.err:     at okhttp3.internal.http.HttpEngine.sendRequest(SourceFile:248)
01-02 11:20:54.503 2940-3666/com.android.browser W/System.err:     at okhttp3.RealCall.getResponse(SourceFile:243)
01-02 11:20:54.503 2940-3666/com.android.browser W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:201)
01-02 11:20:54.503 2940-3666/com.android.browser W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(SourceFile:145)
01-02 11:20:54.504 2940-3666/com.android.browser W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:190)
01-02 11:20:54.504 2940-3666/com.android.browser W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:163)
01-02 11:20:54.504 2940-3666/com.android.browser W/System.err:     at okhttp3.RealCall.execute(SourceFile:57)
01-02 11:20:54.504 2940-3666/com.android.browser W/System.err:     at retrofit2.OkHttpCall.execute(SourceFile:174)
01-02 11:20:54.504 2940-3666/com.android.browser W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(SourceFile:89)
01-02 11:20:54.504 2940-3666/com.android.browser W/System.err:     at miui.browser.e.b.a(SourceFile:138)
01-02 11:20:54.505 2940-3666/com.android.browser W/System.err:     at miui.browser.e.b.a(SourceFile:124)
01-02 11:20:54.505 2940-3666/com.android.browser W/System.err:     at miui.browser.e.a.a(SourceFile:14)
01-02 11:20:54.505 2940-3666/com.android.browser W/System.err:     at miui.browser.a.b$4.run(SourceFile:180)
01-02 11:20:54.505 2940-3666/com.android.browser W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-02 11:20:54.505 2940-3666/com.android.browser W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-02 11:20:54.505 2940-3666/com.android.browser W/System.err:     at java.lang.Thread.run(Thread.java:760)
```

**Comment by dannyZhou** [comment]
```
01-02 11:35:45.013 10050-12439/com.github.xfalcon.vhosts E/DnsChange: query: cpro.baidustatic.com.
01-02 11:35:45.134 10050-12439/com.github.xfalcon.vhosts E/DnsChange: query: m.news.baidu.com.
01-02 11:35:45.195 10050-12440/com.github.xfalcon.vhosts E/TCPInput: Network read error: 202.108.23.152:443:34764
                                                                     java.io.IOException: Connection reset by peer
                                                                         at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
                                                                         at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
                                                                         at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
                                                                         at sun.nio.ch.IOUtil.read(IOUtil.java:192)
                                                                         at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382)
                                                                         at com.github.xfalcon.vhosts.vservice.TCPInput.processInput(TCPInput.java:136)
                                                                         at com.github.xfalcon.vhosts.vservice.TCPInput.run(TCPInput.java:74)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:760)
01-02 11:35:45.263 2940-2940/com.android.browser W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 2940
01-02 11:35:45.359 10050-12440/com.github.xfalcon.vhosts E/TCPInput: Network read error: 111.206.223.251:443:52924
                                                                     java.io.IOException: Connection reset by peer
                                                                         at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
                                                                         at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
                                                                         at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
                                                                         at sun.nio.ch.IOUtil.read(IOUtil.java:192)
                                                                         at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382)
                                                                         at com.github.xfalcon.vhosts.vservice.TCPInput.processInput(TCPInput.java:136)
                                                                         at com.github.xfalcon.vhosts.vservice.TCPInput.run(TCPInput.java:74)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:760)
01-02 11:35:45.475 2940-2940/com.android.browser W/cr_ScreenOrientation: Removing an inexistent observer!
01-02 11:35:45.892 2940-3059/com.android.browser W/TRACE: FL,set=6e7a7a7679403535746b7d793468676f6a7b3469757335746b7d79456c784373756e75736b2c79796f6a43362c6c787573433e3a3a682c7b6f6a432c767b4379802b3a36393836653736363a2b38497a672b3a366f766e75746b6538653d3436653737653f34392c686a6576676d6b657a7f766b43372935.
01-02 11:35:45.894 760-760/? I/MSM-irqbalance: Decided to move IRQ224 from CPU3 to CPU0
01-02 11:35:45.897 2940-2940/com.android.browser W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 2940
01-02 11:35:46.171 10050-12440/com.github.xfalcon.vhosts E/TCPInput: Network read error: 202.108.23.152:443:34824
                                                                     java.io.IOException: Connection reset by peer
                                                                         at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
                                                                         at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
                                                                         at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
                                                                         at sun.nio.ch.IOUtil.read(IOUtil.java:192)
                                                                         at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382)
                                                                         at com.github.xfalcon.vhosts.vservice.TCPInput.processInput(TCPInput.java:136)
                                                                         at com.github.xfalcon.vhosts.vservice.TCPInput.run(TCPInput.java:74)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:760)
```

**Comment by x-falcon** [comment]
What version?Please try the Release version
