### ISSUE TITLE
Get EPIPE (Broken pipe) and ECONNRESET (Connection reset by peer) errors

### ISSUE THREAD

**Issue by ElTuru** [x-falcon/Virtual-Hosts#19]
First of all, thanks Falcon for all your work!
I ported your project into my project, paying special attention to the imports. The VPN starts succesfully, but after I want to browse, after a few seconds I get EPIPE (Broken pipe) and ECONNRESET (Connection reset by peer) errors, and then the phone has all the internet blocked(browser and apps).

**E/TCPInput: Network read error: 156.154.202.36:443:37675**
            java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
                at libcore.io.IoBridge.recvfrom(IoBridge.java:564)
                at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342)
                at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304)
                at ar.com.tag_argentina.hashomer.services.hosts.TCPInput.processInput(TCPInput.java:136)
                at ar.com.tag_argentina.hashomer.services.hosts.TCPInput.run(TCPInput.java:74)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                at java.lang.Thread.run(Thread.java:818)
             Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                at libcore.io.Posix.recvfromBytes(Native Method)
                at libcore.io.Posix.recvfrom(Posix.java:179)
                at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:245)
                at libcore.io.IoBridge.recvfrom(IoBridge.java:561)
                at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342) 
                at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304) 
                at ar.com.tag_argentina.hashomer.services.hosts.TCPInput.processInput(TCPInput.java:136) 
                at ar.com.tag_argentina.hashomer.services.hosts.TCPInput.run(TCPInput.java:74) 
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                at java.lang.Thread.run(Thread.java:818) 

**E/TCPOutput: Network write error: 216.58.202.35:443:32946**
             java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                 at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
                 at libcore.io.IoBridge.sendto(IoBridge.java:525)
                 at java.nio.SocketChannelImpl.writeImpl(SocketChannelImpl.java:403)
                 at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:361)
                 at ar.com.tag_argentina.hashomer.services.hosts.TCPOutput.processACK(TCPOutput.java:240)
                 at ar.com.tag_argentina.hashomer.services.hosts.TCPOutput.run(TCPOutput.java:94)
                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                 at java.lang.Thread.run(Thread.java:818)
              Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
                 at libcore.io.Posix.sendtoBytes(Native Method)
                 at libcore.io.Posix.sendto(Posix.java:201)
                 at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:270)
                 at libcore.io.IoBridge.sendto(IoBridge.java:523)
                 at java.nio.SocketChannelImpl.writeImpl(SocketChannelImpl.java:403) 
                 at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:361) 
                 at ar.com.tag_argentina.hashomer.services.hosts.TCPOutput.processACK(TCPOutput.java:240) 
                 at ar.com.tag_argentina.hashomer.services.hosts.TCPOutput.run(TCPOutput.java:94) 
                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                 at java.lang.Thread.run(Thread.java:818)

**Comment by x-falcon** [comment]
i will update new version, the version too old.
this problem caused by  deadlock

**Comment by ElTuru** [comment]
Can I hire you to fix it on my project?

**Comment by x-falcon** [comment]
what's wrong with your project?

**Comment by ElTuru** [comment]
I copied all the java clases of Virtual Hosts, and imported them to my own project. My goal is to use a fixed host file that is inside assets folder, so I modified the  setupHostFile() method to do this:

`    private void setupHostFile() {

        try {
            AssetManager am = getApplicationContext().getAssets();
            final InputStream inputStream = am.open("host");

            threadHandleHosts = new Thread() {
                public void run() {
                    DnsChange.handle_hosts(inputStream);
                }
            };
            threadHandleHosts.start();
        } catch (Exception e) {
            Log.e(TAG, "error setup host file service", e);
        }
    }`

But, although at first works well, after a few minutes I get Get EPIPE (Broken pipe) and ECONNRESET (Connection reset by peer) errors, and after that all the connection is completely blocked.

I also tried with the example host file(provided in Virtual Hosts GitHub page, but also get the errors).

**Comment by ElTuru** [comment]
Can I hire you to fix the deadlock issue?

**Comment by x-falcon** [comment]
Sorry, Our project is going online.
So, it's too busy
