### ISSUE TITLE
Android 10 Not Support App Crashed

### ISSUE THREAD

**Issue by arifbillah24** [x-falcon/Virtual-Hosts#59]
Samsung Android 10 when on vpn and app Crashed Please Fix it

**Comment by x-falcon** [comment]
I will check

**Comment by arifbillah24** [comment]
android studio debug info please check....


java.lang.RuntimeException: Unable to create service com.github.xfalcon.vhosts.vservice.VhostsService: java.lang.SecurityException: getPackageUid: Neither user 10188 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4293)
        at android.app.ActivityThread.access$1500(ActivityThread.java:270)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: java.lang.SecurityException: getPackageUid: Neither user 10188 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.os.Parcel.createException(Parcel.java:2088)
        at android.os.Parcel.readException(Parcel.java:2056)
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:3999)
        at android.net.VpnService$Builder.establish(VpnService.java:1087)
        at com.github.xfalcon.vhosts.vservice.VhostsService.setupVPN(VhostsService.java:177)
        at com.github.xfalcon.vhosts.vservice.VhostsService.onCreate(VhostsService.java:98)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4281)
        at android.app.ActivityThread.access$1500(ActivityThread.java:270) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7948) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(ContextImpl.java:2001)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2029)
        at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(PermissionManagerService.java:3794)
        at com.android.server.pm.permission.PermissionManagerService.access$2400(PermissionManagerService.java:156)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.enforceCrossUserPermission(PermissionManagerService.java:4040)
2020-08-24 16:37:00.387 15670-15691/com.github.xfalcon.vhosts I/.xfalcon.vhost: Background concurrent copying GC freed 339276(28MB) AllocSpace objects, 2(40KB) LOS objects, 73% free, 6486KB/24MB, paused 255us total 237.158ms
2020-08-24 16:37:01.829 15670-15691/com.github.xfalcon.vhosts I/.xfalcon.vhost: Background young concurrent copying GC freed 411639(14MB) AllocSpace objects, 0(0B) LOS objects, 51% free, 11MB/24MB, paused 183us total 213.242ms
2020-08-24 16:37:02.827 15670-15691/com.github.xfalcon.vhosts I/.xfalcon.vhost: Background concurrent copying GC freed 448141(15MB) AllocSpace objects, 0(0B) LOS objects, 61% free, 11MB/29MB, paused 151us total 261.020ms

**Comment by arifbillah24** [comment]
at com.github.xfalcon.vhosts.vservice.VhostsService.setupVPN(VhostsService.java:177)
        at com.github.xfalcon.vhosts.vservice.VhostsService.onCreate(VhostsService.java:98)

this two line problem i think....

**Comment by nautatva** [comment]
Works perfectly fine on my OnePlus 5T, android 10
